name: Rust Problem Matchers Action
description: Set up Problem Matchers for Rust.
branding:
  color: yellow
  icon: alert-circle
runs:
  using: composite
  steps:
    - name: Set up Problem Matchers for Rust
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/.github/rust-matchers.json"
