name: Rust Problem Matchers
description: Set-up Problem Matchers for Rust.
branding:
  color: purple
  icon: list
runs:
  using: composite
  steps:
    - name: Set-up Problem Matchers for Rust
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/.github/rust-matchers.json"
